'use strict';

const METRIC_CONTRACT_VERSION = 'v2';
const MONEY_DECIMAL_PLACES = 2;
const ZERO_DIVISION_RESULT = null;

module.exports = {
  METRIC_CONTRACT_VERSION,
  MONEY_DECIMAL_PLACES,
  ZERO_DIVISION_RESULT,
};
