'use strict';

const PASS_PERCENT = 80;

const CERTIFICATION_BANK = Object.freeze([
  Object.freeze({
    id: 'CERT-001', moduleCode: 'KNOW-01',
    prompt: 'Для каких кошек в каталоге AWARD предназначена линейка Sterilized?',
    options: Object.freeze(['Для взрослых стерилизованных кошек', 'Для всех котят', 'Только для собак', 'Только для кошек с диагнозом']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-002', moduleCode: 'KNOW-01',
    prompt: 'Что нужно проверить на конкретной упаковке AWARD Sterilized?',
    options: Object.freeze(['Только цвет пачки', 'Только цену', 'Только страну производства', 'Возраст, назначение, вкус/формат и норму кормления']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-003', moduleCode: 'KNOW-01',
    prompt: 'Можно ли переносить свойства одной линейки AWARD на другую?',
    options: Object.freeze(['Да, если упаковки похожи', 'Да, если цена одинаковая', 'Нет, свойства сверяют по конкретному продукту', 'Да, у бренда все свойства одинаковы']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-004', moduleCode: 'KNOW-01',
    prompt: 'Что нельзя обещать по обычному корму Sterilized без указания производителя?',
    options: Object.freeze(['Возрастную категорию', 'Лечебный или профилактический эффект', 'Вкус продукта', 'Вес упаковки']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-005', moduleCode: 'KNOW-02',
    prompt: 'Для кого в каталоге AWARD есть Monoprotein?',
    options: Object.freeze(['Для взрослых кошек, включая отдельные позиции для стерилизованных', 'Только для щенков', 'Только для птиц', 'Только для котят до месяца']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-006', moduleCode: 'KNOW-02',
    prompt: 'Где проверять свойства конкретного AWARD Monoprotein?',
    options: Object.freeze(['В комментариях покупателей', 'В случайном обзоре', 'По памяти', 'На упаковке и в официальном каталоге']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-007', moduleCode: 'KNOW-02',
    prompt: 'Покупатель говорит об аллергии. Что делает продавец?',
    options: Object.freeze(['Сам назначает рацион', 'Советует отменить лечение', 'Не обещает лечение и предлагает обсудить рацион с ветеринаром', 'Гарантирует устранение аллергии']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-008', moduleCode: 'KNOW-02',
    prompt: 'Можно ли считать любой Monoprotein лечебным кормом?',
    options: Object.freeze(['Да, если один белок', 'Нет', 'Да, всегда', 'Да, если дорогой']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-009', moduleCode: 'KNOW-03',
    prompt: 'К какой категории AWARD относит Veterinary Diet?',
    options: Object.freeze(['К ветеринарным диетам', 'К игрушкам', 'К лакомствам', 'К наполнителям']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-010', moduleCode: 'KNOW-03',
    prompt: 'Что рекомендует производитель перед применением Veterinary Diet?',
    options: Object.freeze(['Сменить рацион без консультации', 'Смешивать все диеты', 'Выбирать только по вкусу', 'Консультацию ветеринарного врача']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-011', moduleCode: 'KNOW-03',
    prompt: 'Кто решает продолжительность или смену ветеринарной диеты?',
    options: Object.freeze(['Кассир', 'Другой покупатель', 'Ветеринарный специалист', 'Продавец']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-012', moduleCode: 'KNOW-03',
    prompt: 'Что может сделать продавец с Veterinary Diet?',
    options: Object.freeze(['Назначить лечение', 'Найти нужную позицию и объяснить информацию с упаковки', 'Поставить диагноз', 'Изменить назначение врача']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-013', moduleCode: 'KNOW-04',
    prompt: 'Есть ли один формат корма, лучший для всех животных?',
    options: Object.freeze(['Нет', 'Да, только сухой', 'Да, только влажный', 'Да, самый дорогой']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-014', moduleCode: 'KNOW-04',
    prompt: 'Что сначала уточнить при сравнении сухого и влажного корма?',
    options: Object.freeze(['Цвет миски', 'Породу продавца', 'Размер магазина', 'Текущий рацион, возраст и задачу владельца']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-015', moduleCode: 'KNOW-04',
    prompt: 'По чему сравнивают конкретные рационы?',
    options: Object.freeze(['По случайным отзывам', 'Только по цене', 'По назначению, полнорационности и норме кормления на упаковке', 'По рекламе конкурента']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-016', moduleCode: 'KNOW-04',
    prompt: 'Кто определяет индивидуальную лечебную схему питания?',
    options: Object.freeze(['Поставщик', 'Ветеринарный специалист', 'Продавец', 'Кассир']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-017', moduleCode: 'KNOW-05',
    prompt: 'Можно ли продавцу назначить универсальный срок перехода на новый корм?',
    options: Object.freeze(['Нет', 'Да, всегда 1 день', 'Да, всегда 3 дня', 'Да, всегда 14 дней']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-018', moduleCode: 'KNOW-05',
    prompt: 'Где взять схему перехода на конкретный корм?',
    options: Object.freeze(['В случайном чате', 'По памяти другого покупателя', 'На ценнике', 'На упаковке или в официальной инструкции производителя']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-019', moduleCode: 'KNOW-05',
    prompt: 'Что делать при хроническом заболевании во время смены рациона?',
    options: Object.freeze(['Ускорить переход', 'Самостоятельно отменить лечение', 'Согласовать смену с ветеринаром', 'Игнорировать заболевание']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-020', moduleCode: 'KNOW-05',
    prompt: 'Главный принцип перехода на новый корм в консультации?',
    options: Object.freeze(['Не читать упаковку', 'Следовать инструкции конкретного производителя', 'Использовать одну схему для всех кормов', 'Ориентироваться только на цену']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-021', moduleCode: 'KNOW-06',
    prompt: 'Какие задачи лакомств есть в каталоге «Мнямс»?',
    options: Object.freeze(['В том числе для дрессировки и чистки зубов', 'Только для сна', 'Только для купания', 'Только для перевозки']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-022', moduleCode: 'KNOW-06',
    prompt: 'Что учитывать при подборе лакомства?',
    options: Object.freeze(['Только цвет упаковки', 'Только скидку', 'Только форму логотипа', 'Вид животного, возраст/размер и назначение товара']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-023', moduleCode: 'KNOW-06',
    prompt: 'Где смотреть норму и ограничения лакомства?',
    options: Object.freeze(['По памяти', 'В отзыве неизвестного автора', 'На конкретной упаковке', 'На соседнем товаре']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-024', moduleCode: 'KNOW-06',
    prompt: 'Можно ли одинаково рекомендовать все лакомства «Мнямс»?',
    options: Object.freeze(['Да, если один бренд', 'Нет, назначение конкретного товара различается', 'Да, у них одинаковое назначение', 'Да, если одинаковая цена']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-025', moduleCode: 'KNOW-07',
    prompt: 'Какой тип Cat’s Choice тофу?',
    options: Object.freeze(['Растительный комкующийся', 'Древесный впитывающий', 'Силикагелевый впитывающий', 'Минеральный некомкующийся']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-026', moduleCode: 'KNOW-07',
    prompt: 'Какой тип древесного Cat’s Choice?',
    options: Object.freeze(['Комкующийся тофу', 'Бумажный комкующийся', 'Кормовой', 'Впитывающий']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-027', moduleCode: 'KNOW-07',
    prompt: 'Что спросить перед выбором между тофу и древесным?',
    options: Object.freeze(['Только цвет лотка', 'Только день недели', 'Тип лотка, прошлый наполнитель, важность аромата и способ уборки', 'Только имя кошки']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-028', moduleCode: 'KNOW-07',
    prompt: 'Можно ли объявить один тип наполнителя лучшим без контекста?',
    options: Object.freeze(['Да, самый дорогой', 'Нет', 'Да, всегда тофу', 'Да, всегда древесный']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-029', moduleCode: 'KNOW-08',
    prompt: 'Какие Cat’s Choice относятся к комкующимся?',
    options: Object.freeze(['Растительный тофу и бумажный', 'Древесный и силикагелевый', 'Только древесный', 'Все без исключения']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-030', moduleCode: 'KNOW-08',
    prompt: 'Какие Cat’s Choice относятся к впитывающим?',
    options: Object.freeze(['Тофу и бумажный', 'Только бумажный', 'Все комкующиеся', 'Древесный и силикагелевый']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-031', moduleCode: 'KNOW-08',
    prompt: 'Какая дополнительная позиция есть в каталоге Cat’s Choice?',
    options: Object.freeze(['Ошейник с pH-индикатором', 'Шампунь с pH-индикатором', 'Растительный наполнитель с pH-индикатором', 'Корм с pH-индикатором']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-032', moduleCode: 'KNOW-08',
    prompt: 'Где смотреть способ использования и утилизации?',
    options: Object.freeze(['По универсальному правилу', 'В инструкции конкретной упаковки', 'На ценнике', 'У конкурента']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-033', moduleCode: 'KNOW-09',
    prompt: 'Что уточнить перед продажей противопаразитарного средства?',
    options: Object.freeze(['Вид животного и параметры, требуемые инструкцией, например возраст или вес', 'Только кличку', 'Только цвет шерсти', 'Только стоимость']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-034', moduleCode: 'KNOW-09',
    prompt: 'Можно ли угадывать дозировку средства?',
    options: Object.freeze(['Да, если опытный продавец', 'Да, для постоянного клиента', 'Да, если похожий товар', 'Нет']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-035', moduleCode: 'KNOW-09',
    prompt: 'Где брать интервал обработки и ограничения?',
    options: Object.freeze(['По памяти покупателя', 'В чате соседнего магазина', 'В инструкции производителя', 'В рекламном слогане']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-036', moduleCode: 'KNOW-09',
    prompt: 'Что делать, если покупатель описывает симптомы и просит лечение?',
    options: Object.freeze(['Пообещать излечение', 'Направить к ветеринарному специалисту', 'Назначить препарат самому', 'Отменить назначение врача']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-037', moduleCode: 'KNOW-10',
    prompt: 'По чему подбирают шампунь или средство ухода?',
    options: Object.freeze(['По виду животного, возрасту и задаче, указанным производителем', 'По цвету бутылки', 'По самой высокой цене', 'По совету случайного покупателя']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-038', moduleCode: 'KNOW-10',
    prompt: 'Где смотреть способ применения средства?',
    options: Object.freeze(['На ценнике', 'На соседнем товаре', 'В памяти продавца', 'На упаковке производителя']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-039', moduleCode: 'KNOW-10',
    prompt: 'Что делать при зуде, воспалении или ранах?',
    options: Object.freeze(['Обещать эффект обычного шампуня', 'Игнорировать симптомы', 'Рекомендовать консультацию ветеринара', 'Подобрать лечение самому']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-040', moduleCode: 'KNOW-10',
    prompt: 'Можно ли самостоятельно называть обычный уход «лечебным»?',
    options: Object.freeze(['Да, если нравится покупателю', 'Нет', 'Да, всегда', 'Да, если товар дорогой']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-041', moduleCode: 'KNOW-11',
    prompt: 'Что уточнить перед подбором инструмента для шерсти?',
    options: Object.freeze(['Вид животного, тип и длину шерсти и задачу ухода', 'Только кличку', 'Только цену', 'Только цвет ручки']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-042', moduleCode: 'KNOW-11',
    prompt: 'По чему выбирают размер и назначение инструмента?',
    options: Object.freeze(['По универсальному правилу', 'По внешнему виду упаковки', 'По скидке', 'По данным производителя и размеру питомца']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-043', moduleCode: 'KNOW-11',
    prompt: 'Кому передать вопрос о рискованной процедуре с повреждённой кожей?',
    options: Object.freeze(['Курьеру', 'Другому покупателю', 'Грумеру или ветеринарному специалисту', 'Кассиру']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-044', moduleCode: 'KNOW-11',
    prompt: 'Можно ли демонстрировать рискованные процедуры без подготовки?',
    options: Object.freeze(['Да, если очередь маленькая', 'Нет', 'Да, всегда', 'Да, ради продажи']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-045', moduleCode: 'KNOW-12',
    prompt: 'Что уточнить при выборе игрушки для кошки?',
    options: Object.freeze(['Возраст, привычный тип игры и что уже есть дома', 'Только кличку', 'Только окрас', 'Только стоимость корма']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-046', moduleCode: 'KNOW-12',
    prompt: 'Что проверяют на игрушке и упаковке?',
    options: Object.freeze(['Только штрихкод', 'Только логотип', 'Только скидку', 'Размер, материалы, ограничения и необходимость присмотра']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-047', moduleCode: 'KNOW-12',
    prompt: 'Можно ли продавать повреждённую игрушку?',
    options: Object.freeze(['Да, если покупатель спешит', 'Да, если повреждение заметно', 'Нет', 'Да, со скидкой всегда']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-048', moduleCode: 'KNOW-12',
    prompt: 'Когда нужно отдельно напомнить о присмотре?',
    options: Object.freeze(['Только при покупке корма', 'При мелких деталях, шнурах и других элементах, требующих контроля', 'Никогда', 'Только взрослым кошкам']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-049', moduleCode: 'KNOW-13',
    prompt: 'Что уточнить при выборе игрушки для собаки?',
    options: Object.freeze(['Размер, возраст, тип игры и интенсивность жевания', 'Только породу без других вопросов', 'Только цвет', 'Только цену']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-050', moduleCode: 'KNOW-13',
    prompt: 'Что сверяют по упаковке игрушки?',
    options: Object.freeze(['Только бренд', 'Только страну', 'Только скидку', 'Размер, назначение и ограничения']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-051', moduleCode: 'KNOW-13',
    prompt: 'Можно ли обещать, что игрушка неразрушима?',
    options: Object.freeze(['Да, для крупных собак', 'Да, если резиновая', 'Нет', 'Да, для дорогих игрушек']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-052', moduleCode: 'KNOW-13',
    prompt: 'Что делать с повреждённой игрушкой?',
    options: Object.freeze(['Обещать безопасность', 'Не предлагать её покупателю', 'Продать как новую', 'Скрыть повреждение']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-053', moduleCode: 'KNOW-14',
    prompt: 'По чему подбирают шлейку, ошейник и поводок?',
    options: Object.freeze(['По виду животного, назначению и таблице размеров производителя', 'По одной универсальной мерке', 'По цене', 'По цвету']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-054', moduleCode: 'KNOW-14',
    prompt: 'Какие мерки использовать?',
    options: Object.freeze(['Всегда одну и ту же мерку', 'Мерки другого бренда', 'Никакие', 'Те, которые указаны для конкретной модели']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-055', moduleCode: 'KNOW-14',
    prompt: 'Что проверить при примерке?',
    options: Object.freeze(['Только логотип', 'Только наличие скидки', 'Комфорт и отсутствие возможности легко выскользнуть', 'Только цвет']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-056', moduleCode: 'KNOW-14',
    prompt: 'Можно ли заменять таблицу производителя универсальным правилом?',
    options: Object.freeze(['Да, если модель похожа', 'Нет', 'Да, всегда', 'Да, для постоянных клиентов']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-057', moduleCode: 'KNOW-15',
    prompt: 'Что учитывать при подборе одежды?',
    options: Object.freeze(['Погодную задачу, размер питомца и таблицу производителя', 'Только цвет', 'Только бренд', 'Только скидку']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-058', moduleCode: 'KNOW-15',
    prompt: 'Что проверить при примерке одежды?',
    options: Object.freeze(['Только бирку', 'Только цену', 'Только упаковку', 'Чтобы она не стесняла движения и не натирала']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-059', moduleCode: 'KNOW-15',
    prompt: 'Где смотреть правила ухода за одеждой?',
    options: Object.freeze(['В чате', 'По памяти другого покупателя', 'На ярлыке производителя', 'На ценнике']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-060', moduleCode: 'KNOW-15',
    prompt: 'Можно ли обещать медицинский эффект одежды?',
    options: Object.freeze(['Да, если дорогая', 'Нет', 'Да, всегда', 'Да, если она тёплая']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-061', moduleCode: 'KNOW-16',
    prompt: 'Что продавец может объяснить о добавке?',
    options: Object.freeze(['Состав, назначение, способ применения и ограничения по официальным материалам', 'Гарантированное лечение', 'Совместимость с любыми лекарствами', 'Диагноз животного']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-062', moduleCode: 'KNOW-16',
    prompt: 'Можно ли обещать лечение заболевания добавкой?',
    options: Object.freeze(['Да, всегда', 'Да, если натуральная', 'Да, если дорогая', 'Нет']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-063', moduleCode: 'KNOW-16',
    prompt: 'Можно ли продавцу оценивать совместимость с лекарствами?',
    options: Object.freeze(['Да, по памяти', 'Да, если покупатель просит', 'Нет', 'Да, всегда']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-064', moduleCode: 'KNOW-16',
    prompt: 'При болезни, лекарствах или беременности куда направить покупателя?',
    options: Object.freeze(['К другому покупателю', 'К ветеринарному врачу', 'К кассиру', 'К поставщику']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-065', moduleCode: 'KNOW-17',
    prompt: 'Что уточнить при выборе туалета для кошки?',
    options: Object.freeze(['Размер кошки, текущий лоток, тип наполнителя и неудобство владельца', 'Только кличку', 'Только цвет лотка', 'Только бренд корма']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-066', moduleCode: 'KNOW-17',
    prompt: 'Как сравнивать открытые и закрытые модели?',
    options: Object.freeze(['По универсальному обещанию', 'Только по цене', 'Только по цвету', 'По размерам, конструкции и инструкции производителя']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-067', moduleCode: 'KNOW-17',
    prompt: 'Какие дополнения можно предложить?',
    options: Object.freeze(['Только игрушку', 'Ничего никогда', 'Совместимые лопатку, пакеты и другие аксессуары', 'Любые случайные товары']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-068', moduleCode: 'KNOW-17',
    prompt: 'Главное условие допродажи аксессуара к туалету?',
    options: Object.freeze(['Он стоит у кассы', 'Он реально совместим с выбранным лотком и наполнителем', 'Он самый дорогой', 'Он того же цвета']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-069', moduleCode: 'KNOW-18',
    prompt: 'С чего начинать изучение нового товара?',
    options: Object.freeze(['С упаковки и официального материала производителя', 'С чужого отзыва', 'С догадки', 'С рекламы конкурента']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-070', moduleCode: 'KNOW-18',
    prompt: 'Что фиксировать после изучения?',
    options: Object.freeze(['Только цену', 'Только цвет', 'Только артикул', 'Назначение и 2–3 подтверждённых отличия']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-071', moduleCode: 'KNOW-18',
    prompt: 'Зачем формулировать вопросы покупателю?',
    options: Object.freeze(['Чтобы не читать упаковку', 'Чтобы предложить самый дорогой товар', 'Чтобы понять потребность до предложения товара', 'Чтобы затянуть консультацию']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-072', moduleCode: 'KNOW-18',
    prompt: 'Можно ли додумывать свойства новинки?',
    options: Object.freeze(['Да, ради продажи', 'Нет', 'Да, если похоже на другой товар', 'Да, если покупатель не знает']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-073', moduleCode: 'KNOW-19',
    prompt: 'Какие три вещи выяснить до подбора товара?',
    options: Object.freeze(['Для какого питомца, какая задача и что использовали раньше', 'Только бюджет', 'Только бренд', 'Только кличку']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-074', moduleCode: 'KNOW-19',
    prompt: 'Что дополнительно важно для кормов и ухода?',
    options: Object.freeze(['Только цвет упаковки', 'Только акция', 'Только страна', 'Возраст и параметры, указанные производителем как важные']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-075', moduleCode: 'KNOW-19',
    prompt: 'Сколько вариантов обычно достаточно предложить после уточнения потребности?',
    options: Object.freeze(['Только один самый дорогой', 'Все товары категории', '1–2 подходящих варианта', 'Не меньше десяти']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-076', moduleCode: 'KNOW-19',
    prompt: 'Как объяснять два подходящих варианта?',
    options: Object.freeze(['Сравнить только по цвету', 'Коротко назвать подтверждённое различие', 'Сказать, что один точно лечит', 'Придумать преимущество']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-077', moduleCode: 'KNOW-20',
    prompt: 'Что продавец может объяснять самостоятельно?',
    options: Object.freeze(['Назначение, состав и применение по упаковке или официальным материалам', 'Диагноз', 'Схему лечения', 'Отмену назначения врача']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-078', moduleCode: 'KNOW-20',
    prompt: 'Что продавец не делает?',
    options: Object.freeze(['Не читает упаковку', 'Не сравнивает товары', 'Не помогает найти товар', 'Не ставит диагноз и не назначает лечение']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-079', moduleCode: 'KNOW-20',
    prompt: 'Можно ли менять назначение ветеринарного врача?',
    options: Object.freeze(['Да, если товар закончился', 'Да, если есть акция', 'Нет', 'Да, если покупатель просит']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-080', moduleCode: 'KNOW-20',
    prompt: 'Что делать при описании симптомов и просьбе подобрать лечение?',
    options: Object.freeze(['Игнорировать проблему', 'Рекомендовать ветеринарного специалиста', 'Назначить средство самому', 'Пообещать результат']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-081', moduleCode: 'KNOW-21',
    prompt: 'От какой суммы выдаётся карта «Миски»?',
    options: Object.freeze(['От 2 000 ₽', 'От 500 ₽', 'От 3 500 ₽', 'От 10 000 ₽']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-082', moduleCode: 'KNOW-21',
    prompt: 'Сколько начисляется бонусами?',
    options: Object.freeze(['1%', '10%', '20%', '5%']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-083', moduleCode: 'KNOW-21',
    prompt: 'Сколько действуют бонусы?',
    options: Object.freeze(['1 год', 'Бессрочно', '3 месяца', '7 дней']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-084', moduleCode: 'KNOW-21',
    prompt: 'Какую долю следующей покупки можно оплатить бонусами?',
    options: Object.freeze(['До 100%', 'До 15%', 'До 5%', 'До 50%']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-085', moduleCode: 'KNOW-22',
    prompt: 'К какому классу Craftia относит свои корма на официальном сайте?',
    options: Object.freeze(['Ультрапремиум', 'Эконом', 'Только ветеринарная диета', 'Не корм, а лакомство']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-086', moduleCode: 'KNOW-22',
    prompt: 'Что Craftia указывает как основу продукта?',
    options: Object.freeze(['Сахар', 'Только зерно', 'Искусственные ароматизаторы', 'Свежее мясо']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-087', moduleCode: 'KNOW-22',
    prompt: 'Что официальный сайт Craftia указывает как отсутствующее?',
    options: Object.freeze(['Витамины', 'Белок', 'Эмульгаторы, ароматизаторы, красители и консерванты', 'Мясо']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-088', moduleCode: 'KNOW-22',
    prompt: 'Что сверять перед рекомендацией конкретного Craftia?',
    options: Object.freeze(['Только название бренда', 'Вид и возраст питомца, рецепт, назначение и норму кормления', 'Только цвет пачки', 'Только цену']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-089', moduleCode: 'KNOW-23',
    prompt: 'Для каких питомцев предназначен Bambini Pets?',
    options: Object.freeze(['Для грызунов, кроликов и птиц', 'Только для кошек', 'Только для собак', 'Только для рыб']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-090', moduleCode: 'KNOW-23',
    prompt: 'Какие товары есть у Bambini Pets по официальному сайту?',
    options: Object.freeze(['Только лекарства', 'Только поводки', 'Только кошачьи туалеты', 'Корма, лакомства, наполнители, домики/гамаки, минеральные товары и игрушки']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-091', moduleCode: 'KNOW-23',
    prompt: 'С чего начинать подбор Bambini Pets?',
    options: Object.freeze(['С цвета', 'С самого крупного товара', 'С вида питомца и назначения товара', 'С цены']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-092', moduleCode: 'KNOW-23',
    prompt: 'Что проверить у конкретного аксессуара Bambini Pets?',
    options: Object.freeze(['Только акцию', 'Материал, размер и ограничения на упаковке', 'Только логотип', 'Только штрихкод']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-093', moduleCode: 'KNOW-24',
    prompt: 'Какие категории есть у «Фермы кота Фёдора»?',
    options: Object.freeze(['Сухие и влажные корма и лакомства', 'Только игрушки', 'Только наполнители', 'Только одежда']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-094', moduleCode: 'KNOW-24',
    prompt: 'Для каких групп есть отдельные продукты?',
    options: Object.freeze(['Только для собак', 'Только для птиц', 'Только для грызунов', 'Для взрослых, стерилизованных кошек и котят']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-095', moduleCode: 'KNOW-24',
    prompt: 'Что проверить на конкретном корме бренда?',
    options: Object.freeze(['Только цену', 'Только рекламу', 'Возраст, назначение, полнорационность и норму кормления', 'Только цвет']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-096', moduleCode: 'KNOW-24',
    prompt: 'Можно ли переносить свойства одного продукта на весь бренд?',
    options: Object.freeze(['Да, если один вкус', 'Нет', 'Да, всегда', 'Да, если упаковки похожи']),
    correctIndex: 1,
  }),
  Object.freeze({
    id: 'CERT-097', moduleCode: 'KNOW-25',
    prompt: 'Какие категории представлены в Premium Pet?',
    options: Object.freeze(['Груминг, гигиена, кожа/шерсть, зубы, уши, глаза, наполнители и другие', 'Только корма', 'Только одежда', 'Только поводки']),
    correctIndex: 0,
  }),
  Object.freeze({
    id: 'CERT-098', moduleCode: 'KNOW-25',
    prompt: 'Что различается у конкретных средств Japan Premium Pet?',
    options: Object.freeze(['Только цвет', 'Только цена', 'Только язык на упаковке', 'Зона применения, вид животного, формат и способ использования']),
    correctIndex: 3,
  }),
  Object.freeze({
    id: 'CERT-099', moduleCode: 'KNOW-25',
    prompt: 'На чём основывать консультацию по конкретному средству?',
    options: Object.freeze(['На случайном отзыве', 'На соседнем товаре', 'На официальной карточке и упаковке товара', 'На догадке']),
    correctIndex: 2,
  }),
  Object.freeze({
    id: 'CERT-100', moduleCode: 'KNOW-25',
    prompt: 'Можно ли превращать гигиеническое средство в обещание лечения?',
    options: Object.freeze(['Да, если дорогое', 'Нет', 'Да, всегда', 'Да, если японское']),
    correctIndex: 1,
  }),
]);

function publicCertificationQuestions() {
  return CERTIFICATION_BANK.map(({ correctIndex, ...question }) => question);
}

module.exports = {
  CERTIFICATION_BANK,
  PASS_PERCENT,
  publicCertificationQuestions,
};
