const categories=[['Диффузоры','Аромат как часть интерьера'],['Свечи','Тихий свет и сложные композиции'],['Спреи','Мгновенно изменить настроение'],['Рефилы','Продлить любимый аромат'],['Для автомобиля','Знакомый аромат в дороге'],['Подарки','Готовые знаки внимания']]
const families=['Древесные','Свежие','Цитрусовые','Цветочные','Пряные','Тёплые']
const rooms=['Гостиная','Спальня','Ванная','Кабинет','Прихожая']
const demo=[['№ 01','Hinoki · Cedar · Incense','Древесный / спокойный'],['№ 02','Bergamot · Neroli · Tea','Свежий / светлый'],['№ 03','Fig · Moss · Sandalwood','Зелёный / мягкий'],['№ 04','Amber · Tonka · Leather','Тёплый / глубокий']]
export default function Home(){return <main>
<header className="header"><a className="logo" href="#">VOZDOOH</a><nav><a href="#catalog">Каталог</a><a href="#finder">Подобрать аромат</a><a href="#brands">Бренды</a><a href="#about">О нас</a></nav><div className="actions"><button>Поиск</button><button>Корзина · 0</button></div></header>
<section className="hero"><div className="eyebrow">Премиальная парфюмерия для дома</div><h1>Атмосфера<br/>начинается с аромата.</h1><p>Ароматы, которые становятся частью пространства — так же естественно, как свет, музыка и любимые вещи.</p><div className="heroActions"><a className="primary" href="#catalog">Смотреть коллекцию</a><a className="textLink" href="#finder">Помочь с выбором →</a></div><div className="heroObject"><div className="sticks"/><div className="bottle"><span>VOZDOOH</span><small>HOME FRAGRANCE</small></div><div className="shadow"/></div><span className="edition">CURATED HOME FRAGRANCE · 2026</span></section>
<section id="catalog" className="section"><div className="sectionHead"><div><span className="eyebrow">Каталог</span><h2>Выберите способ<br/>наполнить дом ароматом</h2></div><p>Начните с формата. Реальный ассортимент и наличие появятся здесь после синхронизации с 1С.</p></div><div className="categoryGrid">{categories.map(([n,d],i)=><a className="category" href="#" key={n}><span>0{i+1}</span><h3>{n}</h3><p>{d}</p><b>Смотреть →</b></a>)}</div></section>
<section id="finder" className="finder"><div><span className="eyebrow light">Подбор аромата</span><h2>Как должен<br/>ощущаться ваш дом?</h2><p>Не обязательно знать ноты и парфюмерные термины. Выберите настроение — мы сузим выбор.</p><a className="creamButton" href="#moods">Подобрать аромат</a></div><div id="moods" className="finderOptions"><span>По характеру</span>{families.map((x,i)=><button key={x}><em>0{i+1}</em>{x}<b>→</b></button>)}</div></section>
<section className="section editorial"><div><span className="eyebrow">Кураторский выбор</span><h2>Не сотни случайных позиций.<br/>Только то, что стоит вашего пространства.</h2></div><div className="products">{demo.map(([n,notes,mood],i)=><article key={n}><div className={'productVisual p'+i}><div className="miniSticks"/><div className="miniBottle"><small>VOZDOOH</small><strong>{n}</strong></div></div><div className="productMeta"><span>{mood}</span><h3>{notes}</h3><p>Демонстрационная карточка · цена и наличие из 1С</p></div></article>)}</div></section>
<section className="room"><div><span className="eyebrow light">По пространству</span><h2>У каждой комнаты<br/>свой характер.</h2><p>Мы подскажем интенсивность и направление аромата под назначение пространства.</p></div><div className="roomLinks">{rooms.map((x,i)=><a href="#" key={x}><span>0{i+1}</span>{x}<b>→</b></a>)}</div></section>
<section id="brands" className="section brands"><span className="eyebrow">Бренды</span><div className="sectionHead"><h2>Коллекция без компромиссов.</h2><p>После импорта каталога здесь появятся только бренды, которые действительно есть в ассортименте VOZDOOH.</p></div><div className="brandPlaceholder">REAL BRANDS FROM 1C <span>→</span></div></section>
<section id="about" className="manifesto"><span>VOZDOOH / МАНИФЕСТ</span><p>Мы выбираем аромат не по громкости, а по тому, <i>что он делает с пространством.</i></p><small>Интернет-магазин премиальной парфюмерии для дома</small></section>
<footer><a className="logo" href="#">VOZDOOH</a><p>Каталог · Бренды · Доставка и оплата · Контакты</p><p>© 2026 VOZDOOH</p></footer>
</main>}